# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: python:3.5

stages:
- test
- deploy

before_script:
  - pip install -r requirements.txt

coverage:
  stage: test
  script:
    - py.test --cov-report=html:coverage --cov prob140 --verbose
    - py.test --cov prob140
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
    - coverage

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -rf coverage public
    - cp -r docs/_build/html public
  dependencies:
    - coverage
  artifacts:
    paths:
    - public
  only:
  - master
