# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: python

pages:
  stage: deploy
  script:
  - cp -r _build ../public
  artifacts:
    paths:
    - public
  only:
  - master
