language: python
python:
  - "3.5"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
script:
  - py.test -v --cov prob140 --cov-report term-missing
after_success:
  - coveralls