language: python
env:
  global:
    COVERALLS_REPO_TOKEN=TeiRYz33VCicKLSCi2Oq2rmiX2bQGHodE5SkA
python:
  - "3.5"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
  - pip uninstall -y coveralls
script:
  - py.test -v --cov prob140 --cov-report term-missing
after_success:
  - coveralls
